name: Docker

on:
 workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.USER_DOCKER_HUB }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.2.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: .
          # Path to the Dockerfile
          file: ./Dockerfile
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: vigiber/go_ci:${{github.ref_name}}
      - name: Download main compilado
        uses: actions/download-artifact@v3
        with:
          name: program