name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  quality:
    uses: ./.github/workflows/Quality.yml

  docker:
    needs: quality
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
  
